---
- name: Create a route table for pod to kubelet traffic
  shell: >-
    cache_key="/cache/11-route-table";
    test -f "$cache_key" && exit 0;
    az network route-table create -g '{{ azure_resource_group }}' -n kthw-route-table && \
      touch "$cache_key"

- name: Associate the route table with our subnet
  shell: >-
    cache_key="/cache/11-route-table-associate";
    test -f "$cache_key" && exit 0;
    az network vnet subnet update -g '{{ azure_resource_group }}' -n kthw-subnet \
      --vnet-name kthw --route-table kthw-route-table && touch "$cache_key"

- name: Add routes linking pods to node
  shell: >-
    for idx in $(seq 0 1);
    do \
      cache_key="/cache/11-route-add-${idx}";
      test -f "$cache_key" && exit 0;
      az network route-table route create -g '{{ azure_resource_group }}' \
        --name "kubernetes-route-10-200-${idx}-0-24" \
        --route-table-name kthw-route-table \
        --next-hop-type VirtualAppliance \
        --next-hop-ip-address "10.240.0.2${idx}" \
        --address-prefix "10.200.${idx}.0/24" && touch "$cache_key"
    done
